kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    environment:
      refresh_token:
        from_secret: refresh_token
      sentry_url:
        from_secret: sentry_url
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      repo: registry.mightyhub.net/hnapi/quake_map
      registry: registry.mightyhub.net
      build_args:
        - environment=staging
      build_args_from_env:
        - refresh_token
        - sentry_url