"""init

Revision ID: 18d4944eb6bb
Revises: 
Create Date: 2023-08-16 14:43:17.979786

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '18d4944eb6bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.Column('serial', sa.Integer(), nullable=True),
                    sa.Column('event_time', sa.DateTime(), nullable=True),
                    sa.Column('store_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('data', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_messages_event_id'), 'messages', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_event_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
