logger:
  level: "TRACE"
  # Backtrace: Traces back to the first frame.
  # Only enable that in very rare circumstances.
  backtrace: false
  # Diagnose: Displays variable in traceback. Disable in production.
  diagnose: true
  retention: "10 days"

proxy:
  http: ""
  https: ""

modules: #TODO
  eew: false
  tsunami: true
  p2p_earthquake: false
  shake_level: false
  global_earthquake: false

utilities:
  update_centroid: true
  cors: true

eew:
  target: "svir" # svir or iedred.

tsunami:
  color:
    major_warning: "#B65BD2"
    warning: "#DE3329"
    watch: "#E5A72C"

global_earthquake:
  list_count: 5

debug:
  global_earthquake:
    enabled: false
  tsunami_watch:
    enabled: false
    file: ""
  p2p_info:
    enabled: false
    file: ""
  tsunami:
    enabled: false
    file: ""
  iedred_eew:
    enabled: false
    file: "../../test/assets/iedred_eew.json"
  svir_eew:
    enabled: false
    ignore_outdated: true
    file: "../../test/assets/svir_eew.json"
  kmoni_eew:
    enabled: false
    start_time: "20210213230800"
    image_override:
      enabled: false
      file: ""
  shake_level:
    enabled: false